import type { AppSettings } from "./types";

export type SoundFontInstrument = {
  name: string;
  soundFontId: string;
};

export const PIANO_MIN_MIDI = 21;
export const PIANO_MAX_MIDI = 108;
export const KEYBOARD_HEIGHT = 116;
export const JUDGEMENT_LINE_OFFSET = 14;
export const START_LEAD_IN_SEC = 3;
export const MIN_HOLD_RATIO = 0.55;
export const MIN_HOLD_SEC = 0.18;
export const SETTINGS_STORAGE_KEY = "achromatic-anamnesis-sciopticon-settings";

export const PLAYBACK_SPEEDS = [0.5, 0.75, 1, 1.25, 1.5, 2];
export const AB_REST_BEATS = [2, 3, 4, 5, 6, 7, 8];
export const SOUND_PRESETS: SoundFontInstrument[] = [
  { name: "Acoustic Grand Piano", soundFontId: "acoustic_grand_piano" },
  { name: "Bright Acoustic Piano", soundFontId: "bright_acoustic_piano" },
  { name: "Electric Grand Piano", soundFontId: "electric_grand_piano" },
  { name: "Honky-tonk Piano", soundFontId: "honkytonk_piano" },
  { name: "Electric Piano 1", soundFontId: "electric_piano_1" },
  { name: "Electric Piano 2", soundFontId: "electric_piano_2" },
  { name: "Harpsichord", soundFontId: "harpsichord" },
  { name: "Clavinet", soundFontId: "clavinet" },
  { name: "Celesta", soundFontId: "celesta" },
  { name: "Glockenspiel", soundFontId: "glockenspiel" },
  { name: "Music Box", soundFontId: "music_box" },
  { name: "Vibraphone", soundFontId: "vibraphone" },
  { name: "Marimba", soundFontId: "marimba" },
  { name: "Xylophone", soundFontId: "xylophone" },
  { name: "Tubular Bells", soundFontId: "tubular_bells" },
  { name: "Dulcimer", soundFontId: "dulcimer" },
  { name: "Drawbar Organ", soundFontId: "drawbar_organ" },
  { name: "Percussive Organ", soundFontId: "percussive_organ" },
  { name: "Rock Organ", soundFontId: "rock_organ" },
  { name: "Church Organ", soundFontId: "church_organ" },
  { name: "Reed Organ", soundFontId: "reed_organ" },
  { name: "Accordion", soundFontId: "accordion" },
  { name: "Harmonica", soundFontId: "harmonica" },
  { name: "Tango Accordion", soundFontId: "tango_accordion" },
  { name: "Acoustic Guitar (nylon)", soundFontId: "acoustic_guitar_nylon" },
  { name: "Acoustic Guitar (steel)", soundFontId: "acoustic_guitar_steel" },
  { name: "Electric Guitar (jazz)", soundFontId: "electric_guitar_jazz" },
  { name: "Electric Guitar (clean)", soundFontId: "electric_guitar_clean" },
  { name: "Electric Guitar (muted)", soundFontId: "electric_guitar_muted" },
  { name: "Overdriven Guitar", soundFontId: "overdriven_guitar" },
  { name: "Distortion Guitar", soundFontId: "distortion_guitar" },
  { name: "Guitar Harmonics", soundFontId: "guitar_harmonics" },
  { name: "Acoustic Bass", soundFontId: "acoustic_bass" },
  { name: "Electric Bass (finger)", soundFontId: "electric_bass_finger" },
  { name: "Electric Bass (pick)", soundFontId: "electric_bass_pick" },
  { name: "Fretless Bass", soundFontId: "fretless_bass" },
  { name: "Slap Bass 1", soundFontId: "slap_bass_1" },
  { name: "Slap Bass 2", soundFontId: "slap_bass_2" },
  { name: "Synth Bass 1", soundFontId: "synth_bass_1" },
  { name: "Synth Bass 2", soundFontId: "synth_bass_2" },
  { name: "Violin", soundFontId: "violin" },
  { name: "Viola", soundFontId: "viola" },
  { name: "Cello", soundFontId: "cello" },
  { name: "Contrabass", soundFontId: "contrabass" },
  { name: "Tremolo Strings", soundFontId: "tremolo_strings" },
  { name: "Pizzicato Strings", soundFontId: "pizzicato_strings" },
  { name: "Orchestral Harp", soundFontId: "orchestral_harp" },
  { name: "Timpani", soundFontId: "timpani" },
  { name: "String Ensemble 1", soundFontId: "string_ensemble_1" },
  { name: "String Ensemble 2", soundFontId: "string_ensemble_2" },
  { name: "Synth Strings 1", soundFontId: "synth_strings_1" },
  { name: "Synth Strings 2", soundFontId: "synth_strings_2" },
  { name: "Choir Aahs", soundFontId: "choir_aahs" },
  { name: "Voice Oohs", soundFontId: "voice_oohs" },
  { name: "Synth Choir", soundFontId: "synth_choir" },
  { name: "Orchestra Hit", soundFontId: "orchestra_hit" },
  { name: "Trumpet", soundFontId: "trumpet" },
  { name: "Trombone", soundFontId: "trombone" },
  { name: "Tuba", soundFontId: "tuba" },
  { name: "Muted Trumpet", soundFontId: "muted_trumpet" },
  { name: "French Horn", soundFontId: "french_horn" },
  { name: "Brass Section", soundFontId: "brass_section" },
  { name: "Synth Brass 1", soundFontId: "synth_brass_1" },
  { name: "Synth Brass 2", soundFontId: "synth_brass_2" },
  { name: "Soprano Sax", soundFontId: "soprano_sax" },
  { name: "Alto Sax", soundFontId: "alto_sax" },
  { name: "Tenor Sax", soundFontId: "tenor_sax" },
  { name: "Baritone Sax", soundFontId: "baritone_sax" },
  { name: "Oboe", soundFontId: "oboe" },
  { name: "English Horn", soundFontId: "english_horn" },
  { name: "Bassoon", soundFontId: "bassoon" },
  { name: "Clarinet", soundFontId: "clarinet" },
  { name: "Piccolo", soundFontId: "piccolo" },
  { name: "Flute", soundFontId: "flute" },
  { name: "Recorder", soundFontId: "recorder" },
  { name: "Pan Flute", soundFontId: "pan_flute" },
  { name: "Blown Bottle", soundFontId: "blown_bottle" },
  { name: "Shakuhachi", soundFontId: "shakuhachi" },
  { name: "Whistle", soundFontId: "whistle" },
  { name: "Ocarina", soundFontId: "ocarina" },
  { name: "Lead 1 (square)", soundFontId: "lead_1_square" },
  { name: "Lead 2 (sawtooth)", soundFontId: "lead_2_sawtooth" },
  { name: "Lead 3 (calliope)", soundFontId: "lead_3_calliope" },
  { name: "Lead 4 (chiff)", soundFontId: "lead_4_chiff" },
  { name: "Lead 5 (charang)", soundFontId: "lead_5_charang" },
  { name: "Lead 6 (voice)", soundFontId: "lead_6_voice" },
  { name: "Lead 7 (fifths)", soundFontId: "lead_7_fifths" },
  { name: "Lead 8 (bass + lead)", soundFontId: "lead_8_bass__lead" },
  { name: "Pad 1 (new age)", soundFontId: "pad_1_new_age" },
  { name: "Pad 2 (warm)", soundFontId: "pad_2_warm" },
  { name: "Pad 3 (polysynth)", soundFontId: "pad_3_polysynth" },
  { name: "Pad 4 (choir)", soundFontId: "pad_4_choir" },
  { name: "Pad 5 (bowed)", soundFontId: "pad_5_bowed" },
  { name: "Pad 6 (metallic)", soundFontId: "pad_6_metallic" },
  { name: "Pad 7 (halo)", soundFontId: "pad_7_halo" },
  { name: "Pad 8 (sweep)", soundFontId: "pad_8_sweep" },
  { name: "FX 1 (rain)", soundFontId: "fx_1_rain" },
  { name: "FX 2 (soundtrack)", soundFontId: "fx_2_soundtrack" },
  { name: "FX 3 (crystal)", soundFontId: "fx_3_crystal" },
  { name: "FX 4 (atmosphere)", soundFontId: "fx_4_atmosphere" },
  { name: "FX 5 (brightness)", soundFontId: "fx_5_brightness" },
  { name: "FX 6", soundFontId: "fx_6_goblins" },
  { name: "FX 7 (echoes)", soundFontId: "fx_7_echoes" },
  { name: "FX 8 (sci-fi)", soundFontId: "fx_8_scifi" },
  { name: "Sitar", soundFontId: "sitar" },
  { name: "Banjo", soundFontId: "banjo" },
  { name: "Shamisen", soundFontId: "shamisen" },
  { name: "Koto", soundFontId: "koto" },
  { name: "Kalimba", soundFontId: "kalimba" },
  { name: "Bagpipe", soundFontId: "bagpipe" },
  { name: "Fiddle", soundFontId: "fiddle" },
  { name: "Shanai", soundFontId: "shanai" },
  { name: "Tinkle Bell", soundFontId: "tinkle_bell" },
  { name: "Agogo", soundFontId: "agogo" },
  { name: "Steel Drums", soundFontId: "steel_drums" },
  { name: "Woodblock", soundFontId: "woodblock" },
  { name: "Taiko Drum", soundFontId: "taiko_drum" },
  { name: "Melodic Tom", soundFontId: "melodic_tom" },
  { name: "Synth Drum", soundFontId: "synth_drum" },
  { name: "Reverse Cymbal", soundFontId: "reverse_cymbal" },
  { name: "Guitar Fret Noise", soundFontId: "guitar_fret_noise" },
  { name: "Breath Noise", soundFontId: "breath_noise" },
  { name: "Seashore", soundFontId: "seashore" },
  { name: "Bird Tweet", soundFontId: "bird_tweet" },
  { name: "Telephone Ring", soundFontId: "telephone_ring" },
  { name: "Helicopter", soundFontId: "helicopter" },
  { name: "Applause", soundFontId: "applause" },
  { name: "Gunshot", soundFontId: "gunshot" },
];

export const DEFAULT_SETTINGS: AppSettings = {
  selectedTrackIds: [],
  userKeyRange: { minMidi: 21, maxMidi: 108 },
  playbackSpeed: 1,
  scrollSpeed: 2,
  inputOffsetMs: 0,
  judgementOffsetMs: 0,
  judgementWindowMs: 90,
  showNoteNames: "pitch-octave",
  soundPreset: "Acoustic Grand Piano",
  masterVolume: 0.82,
  reverb: {
    mix: 0.2,
    decay: 2.4,
    damp: 6000,
  },
  keyboardColors: {
    lightKey: "#e8edf4",
    darkKey: "#c9d0dc",
  },
  noteColors: {
    evenNote: "#4fbcff",
    oddNote: "#ffd37c",
  },
  abLoop: {
    enabled: false,
    startSec: null,
    endSec: null,
    restBeats: 4,
  },
  mode: "game",
  selectedMidiInputId: null,
  selectedMidiInputName: null,
};
